Fix a format-extra-args warning
This code doesn't make sense, I think some lines got duplicated while
applying a patch. This bad code is in the fedora-34 branch, not in
grub 2.06-rc1. Fix by reverting to match what's in 2.06-rc1. Since
`grub_util_info` is just used for logging, it doesn't really matter
what goes in here.

```
/build/grub-src/util/grub-install-common.c: In function 'grub_install_make_image_wrap_file':
/build/grub-src/util/grub-install-common.c:562:19: error: too many arguments for format [-Werror=format-extra-args]
  562 |   grub_util_info ("grub-mkimage --directory '%s' --prefix '%s'"
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```